config/routes.rb
Rails.application.routes.draw do


  #Home Route
  root 'home#index'

  #User Routes
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'user/root',to: 'users#dashboard'
  get 'users/dashboard',to: 'users#dashboard'
  get 'users/:id/Assignment',to: 'users#Assignment',as: :users_Assignment
  post 'users/result_create',to: 'users#result_create'
  get 'users/:uid/:mid/result_show',to: 'users#result_show',as: :users_result_show
  get 'users/:id/video',to: 'users#video',as: :users_video
  get 'users/add_bio', to: 'users#add_bio'
  post 'users/bio_create',to: 'users#bio_create'
  get 'users/acc_lock',to: 'users#acc_lock'
  get 'users/:id/profile',to: 'users#profile',as: :users_profile

  #Entres Routes
  devise_for :entres

  get 'entre/root',to: 'entres#dashboard'
  get 'entres/dashboard',to: 'entres#dashboard'
  get 'entres/add_entrebio', to: 'entres#add_entrebio'
  post 'entres/entrebio_create',to: 'entres#entrebio_create'
  post 'entres/:id/attend_create',to: 'entres#attend_create',as: :entres_attend_create
  post 'entres/:id/attend_destroy',to: 'entres#attend_destroy',as: :entres_attend_destroy
  get 'entres/add_money',to: 'entres#add_money'
  post 'entres/fees_deposit',to: 'entres#fees_deposit',as: :entres_fees_deposit

  #Admin Routes

  get 'admins/sign_in',to: 'admins#sign_in'
  post 'admins/create_session',to: 'admins#create_session'
  delete 'admins/sign_out',to: 'admins#sign_out'
  get 'admins/index',to: 'admins#index'
  get 'admins/add_assignment',to: 'admins#add_assignment'
  post 'admins/question_create',to: 'admins#question_create'
  post 'admins/assignment_create',to: 'admins#assignment_create'
  get 'admins/add_module',to: 'admins#add_module'
  post 'admins/module_create',to: 'admins#module_create'
  get 'admins/add_study_material',to: 'admins#add_study_material'
  post 'admins/:id/create_study_material',to: 'admins#create_study_material',as: :create_study_material

end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendanceadmin.rb
class Attendanceadmin < ApplicationRecord
end

app/models/attendanceentre.rb
class Attendanceentre < ApplicationRecord
end

app/models/bio.rb
class Bio < ApplicationRecord
	belongs_to :user
end

app/models/course.rb
class Course < ApplicationRecord
	has_many :mods, dependent: :destroy
end

app/models/entre.rb
class Entre < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    has_one :entrebio     
end

app/models/entrebio.rb
class Entrebio < ApplicationRecord
	belongs_to :entre
end

app/models/field.rb
class Field < ApplicationRecord
end

app/models/mod.rb
class Mod < ApplicationRecord
	belongs_to :course
	has_many :questions
has_attached_file :document
validates_attachment :document, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }
end

app/models/question.rb
class Question < ApplicationRecord
	belongs_to :mod
end

app/models/report.rb
class Report < ApplicationRecord
	belongs_to :user
end

app/models/result.rb
class Result < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :results       
	has_one :bio  
	has_many :reports
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, :except => [:profile]

	def dashboard
		@time=Time.new
		if(current_user.bio.blank?)
			return redirect_to action: 'add_bio'
		end
		@userbio=current_user.bio
		if((@userbio.expirytime-@time)<=0)
			return redirect_to action: 'acc_lock'
		end	
		current_date=@time.day.to_s + "/" + @time.month.to_s + "/" + @time.year.to_s
		@userstatus=Attendanceadmin.where(user_name:@userbio.name, status: 1, date:current_date,area:@userbio.area)
		if(@userstatus.blank?)
			Attendanceadmin.create(user_name:@userbio.name, status: 1, date:current_date,area:@userbio.area)
		end
		@mods=Mod.where(course_id:@userbio.course_id)
	end

	def add_bio
		@courses=Course.all
	end	

	def bio_create
		@course=Course.find(params[:course])
		time=Time.new
		time=time
		Bio.create(user_id:current_user.id,course_id:params[:course],area:params[:area],name:params[:name],fees:0,expirytime:time)
		redirect_to action: 'dashboard'
	end	

	def Assignment
		@results=Result.where(user_id:current_user.id,mod_id:params[:id])
		if(!@results.blank?)
			return redirect_to action:'result_show',uid:current_user.id,mid:params[:id] 
		end	 
		@questions=Question.where(mod_id: params[:id])
	end

	def result_create
		q=Question.where(mod_id: params[:mod_id]).length
		count=0
		for i in 1..q
			quesFind=Question.find(params["ques_id-#{i}".to_sym])
			if(quesFind.answer==params["ques-#{i}".to_sym])
				corr=1
				count=count+1
			else
				corr=0
			end		
			modname=Mod.find(params[:mod_id]).name
			Result.create(user_id: current_user.id, question_id: params["ques_id-#{i}".to_sym], mod_id: params[:mod_id], ans_marked: params["ques-#{i}".to_sym],correct: corr)
		end
			wa=q-count
			Report.create(user_id: current_user.id, mod_id: params[:mod_id],correctans: count,wrongans:wa,modname: modname)
		redirect_to action: 'result_show',uid:current_user.id,mid:params[:mod_id] 

	end	

	def result_show
		@results=Result.where(user_id:params[:uid],mod_id:params[:mid])
		if(@results.blank?)
			redirect_to action: 'dashboard'
		end	
		@questions=Question.where(mod_id: params[:mid])
		@correctAns=Result.where(user_id:params[:uid],mod_id:params[:mid],correct: 1).length
	end	

	def video
		@mod=Mod.find(params[:id])
	end

	def acc_lock
	end	

	def profile
		user=User.find(params[:id])
		@userbio=user.bio
		@reports=Report.where(user_id:params[:id])
		@modlength=Mod.where(course_id:@userbio.course_id).length
		@type="user"
		if(current_user.blank?)
			@type="entre"
		end
	end	
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/_quesfield.html.erb
<li>	
<%= label_tag "ques-#{n}", "ques-#{n}", class: 'cont' %>
<%= text_field_tag "ques-#{n}", "", class: 'cont' %>

<%= label_tag "queshin-#{n}", "queshin-#{n}", class: 'cont' %>
<%= text_field_tag "queshin-#{n}", "", class: 'cont' %>
<br><br><br><br>
	<ul>
		<li>
			<%= label_tag "option1-q#{n}", "option1-q#{n}", class: 'cont' %>
			<%= text_field_tag "option1-q#{n}", "", class: 'cont' %>
		</li>
		<li>
			<%= label_tag "option1hin-q#{n}", "option1hin-q#{n}", class: 'cont' %>
			<%= text_field_tag "option1hin-q#{n}", "", class: 'cont' %>
		</li>
		<br>
		<li>
			<%= label_tag "option2-q#{n}", "option2-q#{n}", class: 'cont' %>
			<%= text_field_tag "option2-q#{n}", "", class: 'cont' %>
		</li>
		<li>
			<%= label_tag "option2hin-q#{n}", "option2hin-q#{n}", class: 'cont' %>
			<%= text_field_tag "option2hin-q#{n}", "", class: 'cont' %>
		</li>
		<br>
		<li>
			<%= label_tag "option3-q#{n}", "option3-q#{n}", class: 'cont' %>
			<%= text_field_tag "option3-q#{n}", "", class: 'cont' %>
		</li>
		<li>
			<%= label_tag "option3hin-q#{n}", "option3hin-q#{n}", class: 'cont' %>
			<%= text_field_tag "option3hin-q#{n}", "", class: 'cont' %>
		</li>

	</ul>

<p>ANSWER(A,B,C)</p>
<%= label_tag "ans-#{n}", "ans-#{n}", class: 'cont' %>
<%= text_field_tag "ans-#{n}", "", class: 'cont' %>	
</li>
<br>
<hr style="background-color: #f8c04d;">
<br>

app/views/admins/add_assignment.html.erb
<head>
	<style type="text/css">
		.butt{
			font-size: 20px;
		}
		.cont{
			height: 30px;
			width:300px;
			background-color: white;
			font-size: 20px;
			margin-left: 20px;
			margin-top: 5px;
			margin-bottom: 5px;
		}

	</style>
</head>
<h1>ADD ASSIGNMENT</h1>
<div class="container">
	<%= form_tag admins_assignment_create_path,method: :post do %>

	<h2>MODULE NAME</h2>
	<%= text_field_tag :mod_name,"",class: 'cont'%>
	<br>
	<h2>QUESTIONS</h2>
	<%= link_to "Add",admins_question_create_path,method: :post,remote: true,class: 'butt' %>

	<ul id="que">
	

	</ul>
	<br>
	<%= submit_tag "Submit" %>

	<% end %>	
</div>

app/views/admins/add_module.html.erb
<head>
	<style type="text/css">
		.butt{
			font-size: 20px;
		}
		.cont{
			height: 30px;
			width:300px;
			background-color: white;
			font-size: 20px;
			margin-left: 20px;
			margin-top: 5px;
			margin-bottom: 5px;
		}

	</style>
</head>
<h1>ADD MODULE</h1>
<div class="container">
	<%= form_tag admins_module_create_path,method: :post do %>

	<h2>MODULE NAME</h2>
	<%= text_field_tag :mod_name,"",class: 'cont'%>
	<br>
	
	<h2>SELECT COURSE</h2>
	<%= select_tag 'course',options_from_collection_for_select(@courses, "id", "name"),style: 'text-transform:capitalize;'%>

	<h2>VIDEO</h2>
	<ul id="que">
	<%= text_field_tag :vid_name,"",class: 'cont'%>

	</ul>
	<br>
	<%= submit_tag "Submit" %>

	<% end %>	
</div>

app/views/admins/add_study_material.html.erb
<h1>Upload Study Material</h1>

<%= form_for @mod, url: create_study_material_path(@mod.id), html: { multipart: true }, method: :post do |form| %>
  <%= form.file_field :document %>
  <%= form.submit %>
<% end %>

app/views/admins/index.html.erb
<h1>WELCOME <%= @signed_in_admin.username %></h1>

 <p><%= link_to "Sign Out",admins_sign_out_path,method: :delete %></p>

 <p><%= link_to "Add New Assignment",admins_add_assignment_path,method: :get %></p>

 <p><%= link_to "Add New Module",admins_add_module_path,method: :get %></p>

app/views/admins/question_create.js.erb
console.log("New Field Created");
<% @n %>
var newField = $('<%= escape_javascript render "quesfield",n: @n%>');

$('#que').prepend(newField);

app/views/admins/sign_in.html.erb
<h1> Admin Sign In</h1>

<%= form_tag admins_create_session_path,method: :post do %>
	<%= label_tag :username %>
	<%= text_field_tag :username %>

	<br>

	<%= label_tag :password %>
	<%= password_field_tag :password %>

	<br>
	<br>
	<%= submit_tag "Sign In" %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="shortcut icon" type="image/x-icon" href="/assets/favicon.ico">
  <title><%= @title %></title>
  </head>

  <body>
    <%= yield %>
  </body>
</html>