config/routes.rb
Rails.application.routes.draw do


  #Home Route
  root 'home#index'

  #User Routes
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'user/root',to: 'users#dashboard'
  get 'users/dashboard',to: 'users#dashboard'
  get 'users/:id/Assignment',to: 'users#Assignment',as: :users_Assignment
  post 'users/result_create',to: 'users#result_create'
  get 'users/:uid/:mid/result_show',to: 'users#result_show',as: :users_result_show
  get 'users/:id/video',to: 'users#video',as: :users_video
  get 'users/add_bio', to: 'users#add_bio'
  post 'users/bio_create',to: 'users#bio_create'
  get 'users/acc_lock',to: 'users#acc_lock'
  get 'users/:id/profile',to: 'users#profile',as: :users_profile

  #Entres Routes
  devise_for :entres

  get 'entre/root',to: 'entres#dashboard'
  get 'entres/dashboard',to: 'entres#dashboard'
  get 'entres/add_entrebio', to: 'entres#add_entrebio'
  post 'entres/entrebio_create',to: 'entres#entrebio_create'
  post 'entres/:id/attend_create',to: 'entres#attend_create',as: :entres_attend_create
  post 'entres/:id/attend_destroy',to: 'entres#attend_destroy',as: :entres_attend_destroy
  get 'entres/add_money',to: 'entres#add_money'
  post 'entres/fees_deposit',to: 'entres#fees_deposit',as: :entres_fees_deposit

  #Admin Routes

  get 'admins/sign_in',to: 'admins#sign_in'
  post 'admins/create_session',to: 'admins#create_session'
  delete 'admins/sign_out',to: 'admins#sign_out'
  get 'admins/index',to: 'admins#index'
  get 'admins/add_assignment',to: 'admins#add_assignment'
  post 'admins/question_create',to: 'admins#question_create'
  post 'admins/assignment_create',to: 'admins#assignment_create'
  get 'admins/add_module',to: 'admins#add_module'
  post 'admins/module_create',to: 'admins#module_create'
  get 'admins/add_study_material',to: 'admins#add_study_material'
  post 'admins/:id/create_study_material',to: 'admins#create_study_material',as: :create_study_material

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :results       
	has_one :bio  
	has_many :reports
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, :except => [:profile]

	def dashboard
		@time=Time.new
		if(current_user.bio.blank?)
			return redirect_to action: 'add_bio'
		end
		@userbio=current_user.bio
		if((@userbio.expirytime-@time)<=0)
			return redirect_to action: 'acc_lock'
		end	
		current_date=@time.day.to_s + "/" + @time.month.to_s + "/" + @time.year.to_s
		@userstatus=Attendanceadmin.where(user_name:@userbio.name, status: 1, date:current_date,area:@userbio.area)
		if(@userstatus.blank?)
			Attendanceadmin.create(user_name:@userbio.name, status: 1, date:current_date,area:@userbio.area)
		end
		@mods=Mod.where(course_id:@userbio.course_id)
	end

	def add_bio
		@courses=Course.all
	end	

	def bio_create
		@course=Course.find(params[:course])
		time=Time.new
		time=time
		Bio.create(user_id:current_user.id,course_id:params[:course],area:params[:area],name:params[:name],fees:0,expirytime:time)
		redirect_to action: 'dashboard'
	end	

	def Assignment
		@results=Result.where(user_id:current_user.id,mod_id:params[:id])
		if(!@results.blank?)
			return redirect_to action:'result_show',uid:current_user.id,mid:params[:id] 
		end	 
		@questions=Question.where(mod_id: params[:id])
	end

	def result_create
		q=Question.where(mod_id: params[:mod_id]).length
		count=0
		for i in 1..q
			quesFind=Question.find(params["ques_id-#{i}".to_sym])
			if(quesFind.answer==params["ques-#{i}".to_sym])
				corr=1
				count=count+1
			else
				corr=0
			end		
			modname=Mod.find(params[:mod_id]).name
			Result.create(user_id: current_user.id, question_id: params["ques_id-#{i}".to_sym], mod_id: params[:mod_id], ans_marked: params["ques-#{i}".to_sym],correct: corr)
		end
			wa=q-count
			Report.create(user_id: current_user.id, mod_id: params[:mod_id],correctans: count,wrongans:wa,modname: modname)
		redirect_to action: 'result_show',uid:current_user.id,mid:params[:mod_id] 

	end	

	def result_show
		@results=Result.where(user_id:params[:uid],mod_id:params[:mid])
		if(@results.blank?)
			redirect_to action: 'dashboard'
		end	
		@questions=Question.where(mod_id: params[:mid])
		@correctAns=Result.where(user_id:params[:uid],mod_id:params[:mid],correct: 1).length
	end	

	def video
		@mod=Mod.find(params[:id])
	end

	def acc_lock
	end	

	def profile
		user=User.find(params[:id])
		@userbio=user.bio
		@reports=Report.where(user_id:params[:id])
		@modlength=Mod.where(course_id:@userbio.course_id).length
		@type="user"
		if(current_user.blank?)
			@type="entre"
		end
	end	
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/add_bio.html.erb
<head>
  <style type="text/css">
    .field{
      text-transform: uppercase;
      font-size: 18px;
    }
    .field input{
      border:2px solid black;
      width: 100%;
    }
    .bord{
      background-color: #f5f5f5;
      border:3px solid black;
      padding: 40px;
    }
    body{
      background-color: #ffc220 !important;
    }

    .actions{
      display: flex;
      justify-content: center;
      padding: 20px;
    }
    .actions input{
      background-color: #ffc220;
      height: 40px;
      width: 100%;
      text-transform: uppercase;
      font-weight: bold;
      font-size: 20px;
      border:2px solid black;
    }
  </style>
</head>

<h1 style="text-align: center;font-size: 80px;text-transform: uppercase; margin-bottom: 0.5em">Add Bio</h1>
<hr class="hrstyle">
<div class="container bord" style="display: flex;justify-content: center;align-items: center;width: 50%;">
  <div>

    <%= form_tag users_bio_create_path,method: :post do %>
    <div class="field">
      <%= label_tag :name %>
      <%= text_field_tag :name %>
    </div>
    <br>

    <div class="field">
      <%= label_tag :area %>
      <%= select_tag 'area',raw("<option>Badli</option><option>Shahbad</option>"),style: 'text-transform:capitalize;' %>
    </div>
    <br>

    <div class="field">
      <%= label_tag :course %>
      <%= select_tag 'course',options_from_collection_for_select(@courses, "id", "name"),style: 'text-transform:capitalize;'%>
     </div>
    <br>
    <%= submit_tag "Submit" %>

    <% end %>
  </div>
</div>

app/views/users/profile.html.erb
<% @title="Unnati Software | Profile" %>
<!DOCTYPE html>
<html>
    <head>
        <title>Solution | Assignment</title>
        <meta name="description" content="">
        <meta name="keywords" content="">
        <meta charset="utf-8">
        <meta name="author" content="Roman Kirichik">
        <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
        
        <!-- Favicons -->
        <link rel="shortcut icon" href="/assets/favicon2.png">
        <link rel="apple-touch-icon" href="/assets/logo12.png">
        <link rel="apple-touch-icon" sizes="72x72" href="/assets/logo13.png">
        <link rel="apple-touch-icon" sizes="114x114" href="/assets/logo11.png">
        
        <!-- CSS -->
        <link rel="stylesheet" href="/assets/bootstrap.min.css">
        <link rel="stylesheet" href="/assets/style.css">
        <link rel="stylesheet" href="/assets/style-responsive.css">
        <link rel="stylesheet" href="/assets/animate.min.css">
        <link rel="stylesheet" href="/assets/vertical-rhythm.min.css">
        <link rel="stylesheet" href="/assets/owl.carousel.css">
        <link rel="stylesheet" href="/assets/magnific-popup.css">


        <style type="text/css">

        * {
        box-sizing: border-box;
        font-family: 'Muli', sans-serif;
    }

    
    #info h1{
        font-size: 40px;
        font-weight: bold;
    }

    #reportcont{
        margin-top: 100px;
        margin-bottom: 100px;
    }
    #reportcont th{
        text-align: center!important;
        border-bottom: 2px solid grey;
    }
    #reportcont td a{
        text-decoration: none;
        font-size: 25px;
        color: grey;
    }
    #reportcont td a:hover{
        text-decoration: underline;
        color: #f8c04d;
    }
</style>



    </head>
    

    <body class="appear-animate" ">
    
    
        
        <!-- Page Loader -->        
        <div class="page-loader">
            <div class="loader">Loading...</div>
        </div>
        <!-- End Page Loader -->
        
        <!-- Page Wrap -->
        <div class="page" id="top">
            
          <!-- Navigation panel -->

            <nav class="main-nav light stick-fixed" style="background-color: #f8f8f8">
                <div class="full-wrapper relative clearfix">
                    <!-- Logo ( * your text or image into link tag *) -->
                    <div class="nav-logo-wrap local-scroll">
                        <a href="#top" class="logo">
                            <img src="/assets/logo2.png" alt="" />
                        </a>
                    </div>
                    <div class="mobile-nav">
                        <i class="fa fa-bars"></i>
                    </div>
                    <!-- Main Menu -->
                  <div class="inner-nav desktop-nav">
                        <ul class="clearlist scroll-nav local-scroll">
                            <% if(@type=="entre") %>
                            <li class="active"><%=link_to "Home",entres_dashboard_path,method: :get%>  </li>
                            <% else %>
                             <li class="active"><%=link_to "Home",users_dashboard_path,method: :get%>  </li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </nav>
            <!-- End Navigation panel -->
            
            
            <!-- Section -->
            <section style="width: 100%; background-color:white ;">
                <div class="relative container align-left" style="padding-top: 75px;">
                   <h1 style="color:#f8c04d; font-weight: bold; font-size: 80px;text-align: center;text-transform: uppercase;border-bottom: 2px solid black;"><%=@userbio.name %></h1>
                   <div style="display: flex;justify-content: space-between;">
                       <div id="info" style="color: #f8c04d;text-transform: uppercase; width: 40%;">
                           <h1><span style="color: grey;">AREA: </span><%= @userbio.area %></h1>
                           <h1><span style="color: grey;">FEES PAID: </span><%= @userbio.fees %></h1>
                        </div>

                    <div style="width: 0.1%;background-color: grey;">
                    

                    </div>
                        <div style="width: 50%">
                            <div class="outer">
                                
                               <div class="inner" style="width: <%= perc=((@reports.length.to_f*100)/@modlength).to_i %>%">
                                </div>
                            </div>
                            <h1 style="color: black;font-weight: bold;text-align: center;font-size: 80px;margin-bottom: 10px"><%= perc %>%</h1>
                            <p><span style="background-color: green;">&nbsp;&nbsp;&nbsp;&nbsp;</span> MODULES COMPLETED: <%= @reports.length %> </p>
                            <p><span style="background-color: red;"> &nbsp;&nbsp;&nbsp;&nbsp;</span> MODULES LEFT: <%= @modlength-@reports.length %></p>

                        </div>

                    </div>
                <hr width="100%" style="background-color: grey;">

                <div style="display: flex; justify-content: space-between;">
                        <div>
  
                          <h1 style="color:grey; font-weight: bold; font-size: 35px;margin-bottom: 0px;width: 260.59px;text-align: center; ">MODULE WISE REPORT </h1>
                            <hr class="hrstyle">
                        </div>

                        <div style="width: 50%">
                        </div>

               </div>


               <table width="100%" id="reportcont">
                    <thead>
                        <tr>
                            <th style="font-size: 30px;color:grey;width:40%;border-right: 2px solid grey;">MODULE</th>
                            <th style="font-size: 20px;color: green;">CORRECT ANSWERS</th>
                            <th style="font-size: 20px;color: red;">WRONG ANSWERS</th>
                            <th style="font-size: 20px;color: #f8c04d;">PERCENTAGE</th>
                        </tr>    
                    </thead>
                   <tbody style="text-align: center;">
                        <% @reports.each do |r| %>
                        <tr>
                           <td style="font-size: 40px;color: grey;border-right: 2px solid grey;"><%=link_to "#{r.modname}",users_result_show_path(r.user_id,r.mod_id),method: :get%>  </td>
                           <td style="font-size: 15px;color: green;"><%= r.correctans %></td>
                           <td style="font-size: 15px;color: red;"><%= r.wrongans %></td>
                           <td style="font-size: 15px;color: #f8c04d;">
                            <% per=(r.correctans.to_f*100)/(r.correctans+r.wrongans) %>
                            <%= per.to_i %>%
                           </td>
                        </tr>   
                        <% end %>
                   </tbody>
               </table>
                </div>
            </section>
            <!-- End Section -->

            
            
            <!-- Divider -->
            <hr class="mt-0 mb-0 "/>
            <!-- End Divider -->
            



                        <!-- Footer -->
            <footer class="page-section bg-gray-lighter footer pb-40" style="padding-top: 50px;">
                <div style="display: flex; justify-content: space-around;">
                    
                    <div style="width: 20%;text-align: center; color: black;letter-spacing: 0.2em;">
                        <hr class="hrstyle">
                        <h2>ABOUT ENACTUS DTU</h2>
                        <p>WE, at Enactus DTU, apply entrepreneurial concepts to develop dynamic projects that take advantage of people’s inherent dexterity and aptitude at the center of improving their livelihoods.</p>
                        <hr class="hrstyle">
                    </div>

                    <div>
                                <!-- Footer Logo -->
                                <div style="display: flex;justify-content: center;">
                                    <div class="local-scroll wow fadeInUp" data-wow-duration="1.2s" style="width: 50%;">
                                        <a href="#top"><img src="/assets/Unnati.png" width="150" height="150" alt="" /></a>&nbsp;
                                    </div>
                                </div>
                                <!-- End Footer Logo -->

                                <div style="display: flex;justify-content: center;margin-bottom: 20px; ">
                                 <div style="width: 1px;height:50px;background-color:grey">
                                     
                                 </div>
                              </div>

                                <!-- Social Links -->
                                <div class="footer-social-links mb-xs-40">
                                    <a title="Facebook" target="_blank"><i class="fa fa-facebook"></i></a>
                                    <a title="Twitter" target="_blank"><i class="fa fa-twitter"></i></a>
                                    <a title="Instagarm" target="_blank"><i class="fa fa-instagram"></i></a>
                                    <a title="wordpress" target="_blank"><i class="fa fa-wordpress"></i></a>
                                    <a title="Linkedin" target="_blank"><i class="fa fa-linkedin"></i></a>

                                </div>
                                <!-- End Social Links -->  
                                
                                <div style="display: flex;justify-content: center;margin-top:20px;margin-bottom: 10px; ">
                                 <div style="width: 1px;height:50px;background-color:grey">
                                     
                                 </div>
                              </div>
                                <!-- Footer Text -->
                                <div class="footer-text">
                                    <div class="footer-made">
                                        Made With <span style="color: #e25555;">&hearts;</span> by Enactus, Delhi Technological University
                                    </div>
                                </div>
                        <!-- End Footer Text --> 
                        

                     </div>


                     <div style="width: 20%;text-align: center; color: black;letter-spacing: 0.2em;">
                      
                      <hr class="hrstyle">
                       <h2 style="margin-bottom: 5px;">FACING AN ISSUE?</h2>
                        <h4>CONTACT US</h4>
                        <p>Mail Us:<br><a HREF="mailto:unnati.enactus.dtu@gmail.com">unnati.enactus.dtu@gmail.com</a></p>
                         <hr class="hrstyle">

                     </div>


                </div>
            </footer>

            <!-- End Footer -->
        
        
        </div>
        <!-- End Page Wrap -->
        
        
        <!-- JS -->
        <script type="text/javascript" src="/assets/jquery-1.11.2.min.js"></script>
        <script type="text/javascript" src="/assets/jquery.easing.1.3.js"></script>
        <script type="text/javascript" src="/assets/bootstrap.min.js"></script>
        <script type="text/javascript" src="/assets/SmoothScroll.js"></script>
        <script type="text/javascript" src="/assets/jquery.scrollTo.min.js"></script>
        <script type="text/javascript" src="/assets/jquery.localScroll.min.js"></script>
        <script type="text/javascript" src="/assets/jquery.viewport.mini.js"></script>
        <script type="text/javascript" src="/assets/jquery.countTo.js"></script>
        <script type="text/javascript" src="/assets/jquery.appear.js"></script>
        <script type="text/javascript" src="/assets/jquery.sticky.js"></script>
        <script type="text/javascript" src="/assets/jquery.parallax-1.1.3.js"></script>
        <script type="text/javascript" src="/assets/jquery.fitvids.js"></script>
        <script type="text/javascript" src="/assets/owl.carousel.min.js"></script>
        <script type="text/javascript" src="/assets/isotope.pkgd.min.js"></script>
        <script type="text/javascript" src="/assets/imagesloaded.pkgd.min.js"></script>
        <script type="text/javascript" src="/assets/jquery.magnific-popup.min.js"></script>
        <script type="text/javascript" src="/assets/wow.min.js"></script>
        <script type="text/javascript" src="/assets/masonry.pkgd.min.js"></script>
        <script type="text/javascript" src="/assets/jquery.simple-text-rotator.min.js"></script>
        <script type="text/javascript" src="/assets/all.js"></script>
        <script type="text/javascript" src="/assets/contact-form.js"></script>
        <script type="text/javascript" src="/assets/jquery.ajaxchimp.min.js"></script>

<script src="/assets/main.js"></script> <!-- Resource jQuery -->
    </body>
</html>

app/views/users/video.html.erb
<% @title="Unnati Software | Video" %>
<!DOCTYPE html>
<html style="margin: 0px;">
    <head>
        <meta name="description" content="">
        <meta name="keywords" content="">
        <meta charset="utf-8">
        <meta name="author" content="Roman Kirichik">
        <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
        
        <!-- CSS -->
        <link rel="stylesheet" href="/assets/bootstrap.min.css">
        <link rel="stylesheet" href="/assets/style.css">
        <link rel="stylesheet" href="/assets/style-responsive.css">
        <link rel="stylesheet" href="/assets/animate.min.css">
        <link rel="stylesheet" href="/assets/vertical-rhythm.min.css">
        <link rel="stylesheet" href="/assets/owl.carousel.css">
        <link rel="stylesheet" href="/assets/magnific-popup.css">
        
    </head>
	

    <body class="appear-animate">

	
	
        
        <!-- Page Loader -->        
        <div class="page-loader">
            <div class="loader">Loading...</div>
        </div>
        <!-- End Page Loader -->
        
        <!-- Page Wrap -->
        <div class="page" id="top">
            
          <!-- Navigation panel -->

            <nav class="main-nav light stick-fixed" style="background-color: #f8f8f8">
                <div class="full-wrapper relative clearfix">
                    <!-- Logo ( * your text or image into link tag *) -->
                    <div class="nav-logo-wrap local-scroll">
                        <a href="#top" class="logo">
                            <img src="/assets/logo2.png" alt="" />
                        </a>
                    </div>
                    <div class="mobile-nav">
                        <i class="fa fa-bars"></i>
                    </div>
                    <!-- Main Menu -->
                    <div class="inner-nav desktop-nav">
                        <ul class="clearlist scroll-nav local-scroll">
                           <li><%=link_to "Home",users_dashboard_path,method: :get%></li>
                           <li><%=link_to "Assignment",users_Assignment_path(params[:id]),method: :get%></li>
                        </ul>
                    </div>
                </div>
            </nav>
            <!-- End Navigation panel -->
            
            
            <!-- Section -->
            <section style="width: 100%; padding-bottom:40px;background-color: #f8c04d">
                <div class="relative container align-left" style="padding-top: 75px;">
                        
                   <h1 style="color:black;font-family: Open Sans; font-size: 70px; text-align: center;margin-bottom: 10px;text-transform: uppercase;"><%= @mod.name %></h1>
                   <hr class="hrstyle" style="margin-bottom: 40px;">
<!--                     <iframe width="1140" height="600" 
                    src="https://www.youtube.com/embed/qOIY06leYX4" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>">
                </iframe> -->

            <%= video_tag "/assets/#{@mod.video}", :size => "1140x400", :controls => true,:controlsList => "nodownload",style: 'margin:0px;' %>
                <br>
                <br>
                <div style="display:flex;justify-content: flex-end;">
                    <div id="vid" style="width: 190px;height: 70px;">
                  <%=link_to "ASSIGNMENT<i class='fa fa-chevron-right'></i>".html_safe,users_Assignment_path(params[:id]),method: :get%> 
                    </div>
                </div>  
                </div>   

               
            </section>
            <!-- End Section -->
            

        
            <!-- Footer -->
            <footer class="page-section bg-gray-lighter footer pb-40" style="padding-top: 50px;">
                <div style="display: flex; justify-content: space-around;">
                    
                    <div style="width: 20%;text-align: center; color: black;letter-spacing: 0.2em;">
                        <hr class="hrstyle">
                        <h2>ABOUT ENACTUS DTU</h2>
                        <p>WE, at Enactus DTU, apply entrepreneurial concepts to develop dynamic projects that take advantage of people’s inherent dexterity and aptitude at the center of improving their livelihoods.</p>
                        <hr class="hrstyle">
                    </div>

                    <div>
                                <!-- Footer Logo -->
                                <div style="display: flex;justify-content: center;">
                                    <div class="local-scroll wow fadeInUp" data-wow-duration="1.2s" style="width: 50%;">
                                        <a href="#top"><img src="/assets/Unnati.png" width="150" height="150" alt="" /></a>&nbsp;
                                    </div>
                                </div>
                                <!-- End Footer Logo -->

                                <div style="display: flex;justify-content: center;margin-bottom: 20px; ">
                                 <div style="width: 1px;height:50px;background-color:grey">
                                     
                                 </div>
                              </div>

                                <!-- Social Links -->
                                <div class="footer-social-links mb-xs-40">
                                    <a title="Facebook" target="_blank"><i class="fa fa-facebook"></i></a>
                                    <a title="Twitter" target="_blank"><i class="fa fa-twitter"></i></a>
                                    <a title="Instagarm" target="_blank"><i class="fa fa-instagram"></i></a>
                                    <a title="wordpress" target="_blank"><i class="fa fa-wordpress"></i></a>
                                    <a title="Linkedin" target="_blank"><i class="fa fa-linkedin"></i></a>

                                </div>
                                <!-- End Social Links -->  
                                
                                <div style="display: flex;justify-content: center;margin-top:20px;margin-bottom: 10px; ">
                                 <div style="width: 1px;height:50px;background-color:grey">
                                     
                                 </div>
                              </div>
                                <!-- Footer Text -->
                                <div class="footer-text">
                                    <div class="footer-made">
                                        Made With <span style="color: #e25555;">&hearts;</span> by Enactus, Delhi Technological University
                                    </div>
                                </div>
                        <!-- End Footer Text --> 
                        

                     </div>


                     <div style="width: 20%;text-align: center; color: black;letter-spacing: 0.2em;">
                      
                      <hr class="hrstyle">
                       <h2 style="margin-bottom: 5px;">FACING AN ISSUE?</h2>
                        <h4>CONTACT US</h4>
                        <p>Mail Us:<br><a HREF="mailto:unnati.enactus.dtu@gmail.com">unnati.enactus.dtu@gmail.com</a></p>
                         <hr class="hrstyle">

                     </div>


                </div>
            </footer>

            <!-- End Footer -->
        </div>
        <!-- End Page Wrap -->
        
        
        <!-- JS -->
        <script type="text/javascript" src="/assets/jquery-1.11.2.min.js"></script>
        <script type="text/javascript" src="/assets/jquery.easing.1.3.js"></script>
        <script type="text/javascript" src="/assets/bootstrap.min.js"></script>
        <script type="text/javascript" src="/assets/SmoothScroll.js"></script>
        <script type="text/javascript" src="/assets/jquery.scrollTo.min.js"></script>
        <script type="text/javascript" src="/assets/jquery.localScroll.min.js"></script>
        <script type="text/javascript" src="/assets/jquery.viewport.mini.js"></script>
        <script type="text/javascript" src="/assets/jquery.countTo.js"></script>
        <script type="text/javascript" src="/assets/jquery.appear.js"></script>
        <script type="text/javascript" src="/assets/jquery.sticky.js"></script>
        <script type="text/javascript" src="/assets/jquery.parallax-1.1.3.js"></script>
        <script type="text/javascript" src="/assets/jquery.fitvids.js"></script>
        <script type="text/javascript" src="/assets/owl.carousel.min.js"></script>
        <script type="text/javascript" src="/assets/isotope.pkgd.min.js"></script>
        <script type="text/javascript" src="/assets/imagesloaded.pkgd.min.js"></script>
        <script type="text/javascript" src="/assets/jquery.magnific-popup.min.js"></script>
        <script type="text/javascript" src="/assets/gmap3.min.js"></script>
        <script type="text/javascript" src="/assets/wow.min.js"></script>
        <script type="text/javascript" src="/assets/masonry.pkgd.min.js"></script>
        <script type="text/javascript" src="/assets/jquery.simple-text-rotator.min.js"></script>
        <script type="text/javascript" src="/assets/all.js"></script>
        <script type="text/javascript" src="/assets/contact-form.js"></script>
        <script type="text/javascript" src="/assets/jquery.ajaxchimp.min.js"></script>
            </footer>
        </body>
</html>