config/routes.rb
Rails.application.routes.draw do


  #Home Route
  root 'home#index'

  #User Routes
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'user/root',to: 'users#dashboard'
  get 'users/dashboard',to: 'users#dashboard'
  get 'users/:id/Assignment',to: 'users#Assignment',as: :users_Assignment
  post 'users/result_create',to: 'users#result_create'
  get 'users/:uid/:mid/result_show',to: 'users#result_show',as: :users_result_show
  get 'users/:id/video',to: 'users#video',as: :users_video
  get 'users/add_bio', to: 'users#add_bio'
  post 'users/bio_create',to: 'users#bio_create'
  get 'users/acc_lock',to: 'users#acc_lock'
  get 'users/:id/profile',to: 'users#profile',as: :users_profile

  #Entres Routes
  devise_for :entres

  get 'entre/root',to: 'entres#dashboard'
  get 'entres/dashboard',to: 'entres#dashboard'
  get 'entres/add_entrebio', to: 'entres#add_entrebio'
  post 'entres/entrebio_create',to: 'entres#entrebio_create'
  post 'entres/:id/attend_create',to: 'entres#attend_create',as: :entres_attend_create
  post 'entres/:id/attend_destroy',to: 'entres#attend_destroy',as: :entres_attend_destroy
  get 'entres/add_money',to: 'entres#add_money'
  post 'entres/fees_deposit',to: 'entres#fees_deposit',as: :entres_fees_deposit

  #Admin Routes

  get 'admins/sign_in',to: 'admins#sign_in'
  post 'admins/create_session',to: 'admins#create_session'
  delete 'admins/sign_out',to: 'admins#sign_out'
  get 'admins/index',to: 'admins#index'
  get 'admins/add_assignment',to: 'admins#add_assignment'
  post 'admins/question_create',to: 'admins#question_create'
  post 'admins/assignment_create',to: 'admins#assignment_create'
  get 'admins/add_module',to: 'admins#add_module'
  post 'admins/module_create',to: 'admins#module_create'
  get 'admins/add_study_material',to: 'admins#add_study_material'
  post 'admins/:id/create_study_material',to: 'admins#create_study_material',as: :create_study_material

end

app/models/entre.rb
class Entre < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    has_one :entrebio     
end

app/controllers/entres_controller.rb
class EntresController < ApplicationController
	before_action :authenticate_entre!

	def dashboard
		if(current_entre.entrebio.blank?)
			return redirect_to action: 'add_entrebio'
		end
		@entrebio=current_entre.entrebio
		@time=Time.new
		@current_date=@time.day.to_s + "/" + @time.month.to_s + "/" + @time.year.to_s
		# @attendance=Attendanceentre.where(status:1,date:current_date,area:@userbio.area)
		@users=Bio.where(area:@entrebio.area)
	end

	def add_entrebio
	
	end

	def entrebio_create
		Entrebio.create(entre_id:current_entre.id,area:params[:area],name:params[:name],money:0)
		redirect_to action: 'dashboard'
	end	


	def attend_create
		@time=Time.new
		current_date=@time.day.to_s + "/" + @time.month.to_s + "/" + @time.year.to_s
		@userbio=User.find(params[:id]).bio
		Attendanceentre.create(user_name:@userbio.name,user_id:params[:id],status:1,date:current_date,area:@userbio.area)
		redirect_to action: 'dashboard'
	end

	def attend_destroy
		@time=Time.new
		current_date=@time.day.to_s + "/" + @time.month.to_s + "/" + @time.year.to_s
		@userbio=User.find(params[:id]).bio
		a=Attendanceentre.where(user_id:params[:id],status:1,date:current_date,area:@userbio.area).first
		a.delete
		redirect_to action: 'dashboard'
	end	

	def add_money
		@entrebio=current_entre.entrebio
		@users=Bio.where(area:@entrebio.area)
	end	

	def fees_deposit
		bio=Bio.find_by(user_id:params[:user])
		biofees=bio.fees+params[:fees].to_i
		bio.fees=biofees
		time=bio.expirytime+((6.to_f/20)*params[:fees].to_i)*(60*24*60)
		bio.expirytime=time
		bio.save
		redirect_to action: 'dashboard'
	end
end	

app/views/entres/add_entrebio.html.erb
<head>
  <style type="text/css">
    .field{
      text-transform: uppercase;
      font-size: 18px;
    }
    .field input{
      border:2px solid black;
      width: 100%;
    }
    .bord{
      background-color: #f5f5f5;
      border:3px solid black;
      padding: 40px;
    }
    body{
      background-color: #ffc220 !important;
    }

    .actions{
      display: flex;
      justify-content: center;
      padding: 20px;
    }
    .actions input{
      background-color: #ffc220;
      height: 40px;
      width: 100%;
      text-transform: uppercase;
      font-weight: bold;
      font-size: 20px;
      border:2px solid black;
    }
  </style>
</head>

<h1 style="text-align: center;font-size: 80px;text-transform: uppercase; margin-bottom: 0.5em">Add Bio</h1>
<hr class="hrstyle">
<div class="container bord" style="display: flex;justify-content: center;align-items: center;width: 50%;">
  <div>

    <%= form_tag entres_entrebio_create_path,method: :post do %>
    <div class="field">
      <%= label_tag :name %>
      <%= text_field_tag :name %>
    </div>
    <br>

    <div class="field">
      <%= label_tag :area %>
      <%= select_tag 'area',raw("<option>Badli</option><option>Shahbad</option>"),style: 'text-transform:capitalize;' %>
    </div>
    <br>

    <br>
    <%= submit_tag "Submit" %>

    <% end %>
  </div>
</div>

app/views/entres/add_money.html.erb
<% @title="Unnati Software | Add Fees" %>
<head>
  <style type="text/css">
    .field{
      text-transform: uppercase;
      font-size: 18px;
    }
    .field input{
      border:2px solid black;
      width: 100%;
    }
    .bord{
      background-color: #f5f5f5;
      border:3px solid black;
      padding: 40px;
    }
    body{
      background-color: #ffc220 !important;
    }

    .actions{
      display: flex;
      justify-content: center;
      padding: 20px;
    }
    .actions input{
      background-color: #ffc220;
      height: 40px;
      width: 100%;
      text-transform: uppercase;
      font-weight: bold;
      font-size: 20px;
      border:2px solid black;
    }
  </style>
</head>

<h1 style="text-align: center;font-size: 80px;text-transform: uppercase; margin-bottom: 0.5em">Add Money</h1>
<hr class="hrstyle">
<div class="container bord" style="display: flex;justify-content: center;align-items: center;width: 50%;margin-top: 100px;">
  <div>

    <%= form_tag entres_fees_deposit_path,method: :post do %>
    <div class="field">
      <%= label_tag :user %>
      <%= select_tag 'user',options_from_collection_for_select(@users, "user_id", "name"),style: 'text-transform:capitalize;'%>

    </div>
    <br>

    <div class="field">
      <%= label_tag :fees %>
      <%= number_field_tag 'fees' %>
     </div>
    <br>
    <%= submit_tag "Submit" %>

    <% end %>
  </div>
</div>

app/views/entres/change_user_password.html.erb
<% @title="Unnati Software | Add Fees" %>
<head>
  <style type="text/css">
    .field{
      text-transform: uppercase;
      font-size: 18px;
    }
    .field input{
      border:2px solid black;
      width: 100%;
    }
    .bord{
      background-color: #f5f5f5;
      border:3px solid black;
      padding: 40px;
    }
    body{
      background-color: #ffc220 !important;
    }

    .actions{
      display: flex;
      justify-content: center;
      padding: 20px;
    }
    .actions input{
      background-color: #ffc220;
      height: 40px;
      width: 100%;
      text-transform: uppercase;
      font-weight: bold;
      font-size: 20px;
      border:2px solid black;
    }
  </style>
</head>

<h1 style="text-align: center;font-size: 80px;text-transform: uppercase; margin-bottom: 0.5em">CHANGE USER PASSWORD</h1>
<hr class="hrstyle">
<div class="container bord" style="display: flex;justify-content: center;align-items: center;width: 50%;margin-top: 100px;">
  <div>

    <%= form_tag entres_fees_deposit_path,method: :post do %>
    <div class="field">
      <%= label_tag :user %>
      <%= select_tag 'user',options_from_collection_for_select(@users, "user_id", "name"),style: 'text-transform:capitalize;'%>

    </div>
    <br>

    <div class="field">
      <%= label_tag :fees %>
      <%= number_field_tag 'fees' %>
     </div>
    <br>
    <%= submit_tag "Submit" %>

    <% end %>
  </div>
</div>

app/views/entres/dashboard.html.erb
<% @title="Unnati Software | Dashboard" %>
<!DOCTYPE html>
<html>
    <head>
        <meta name="description" content="">
        <meta name="keywords" content="">
        <meta charset="utf-8">
        <meta name="author" content="Roman Kirichik">
        <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
        
        <!-- Favicons -->
        <link rel="shortcut icon" href="/assets/favicon2.png">
        <link rel="apple-touch-icon" href="/assets/logo12.png">
        <link rel="apple-touch-icon" sizes="72x72" href="/assets/logo13.png">
        <link rel="apple-touch-icon" sizes="114x114" href="/assets/logo11.png">
        
        <!-- CSS -->
        <link rel="stylesheet" href="/assets/bootstrap.min.css">
        <link rel="stylesheet" href="/assets/style.css">
        <link rel="stylesheet" href="/assets/style-responsive.css">
        <link rel="stylesheet" href="/assets/animate.min.css">
        <link rel="stylesheet" href="/assets/vertical-rhythm.min.css">
        <link rel="stylesheet" href="/assets/owl.carousel.css">
        <link rel="stylesheet" href="/assets/magnific-popup.css">
            <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>


        <style type="text/css">

        * {
        box-sizing: border-box;
        font-family: 'Muli', sans-serif;
        }
        th{
            text-align: center;
            color: black;
            height: 80px; 
            border:1px solid grey;
        }
        td{
           height: 70px; 
           border:1px solid grey;
        }

        .marked{
            color: green!important;
            text-decoration: none!important;
            font-size: 20px;

        }

        .mark_attend{
            color: red!important;
            text-decoration: none!important;
            font-size: 20px;
        }
        .under{
             text-decoration: none!important;
        }
        .mark_attend:hover{
            text-decoration: underline!important;
        }
        .under:hover{
            text-decoration: underline!important;
        }
        .nme:hover
        {
            background-color: #f8c04d;
        }
</style>



    </head>
    

    <body class="appear-animate" ">
    
    
        
        <!-- Page Loader -->        
        <div class="page-loader">
            <div class="loader">Loading...</div>
        </div>
        <!-- End Page Loader -->
        
        <!-- Page Wrap -->
        <div class="page" id="top">
            
          <!-- Navigation panel -->

            <nav class="main-nav light stick-fixed" style="background-color: #f8f8f8">
                <div class="full-wrapper relative clearfix">
                    <!-- Logo ( * your text or image into link tag *) -->
                    <div class="nav-logo-wrap local-scroll">
                        <a href="#top" class="logo">
                            <img src="/assets/logo2.png" alt="" />
                        </a>
                    </div>
                    <div class="mobile-nav">
                        <i class="fa fa-bars"></i>
                    </div>
                    <!-- Main Menu -->
                  <div class="inner-nav desktop-nav">
                        <ul class="clearlist scroll-nav local-scroll">
                            <li><%=link_to "Home",entres_dashboard_path,method: :get%>  </li>
                            <li><%=link_to "Add fees",entres_add_money_path,method: :get%>  </li>
                            <li><%=link_to "Sign Out",destroy_entre_session_path,method: :delete%>  </li>
                        </ul>
                    </div>
                </div>
            </nav>
            <!-- End Navigation panel -->
            
            
            <!-- Section -->
            <section style="width: 100%; background-color:white ;">
                <div class="relative container align-left" style="padding-top: 75px;">
                   <h1 style="color:#f8c04d; font-weight: bold; font-size: 50px;">WELCOME ADMIN!</h1>
                
                 <div style="display: flex; justify-content: space-between;">
                        <div>
  
                          <h1 style="color:grey; font-weight: bold; font-size: 35px;margin-bottom: 0px; ">TOTAL STUDENTS ENROLLED: </h1>
                            <hr class="hrstyle">

                        </div>
                        <div style="width: 0.1%;background-color: grey;">
                    
                        </div>

                        <div style="width: 50%">
                            
                            <h1 style="color:#f8c04d ;font-family: Open Sans;font-size: 80px;letter-spacing:0.2em; margin-bottom: 10px; margin-top: 0px;text-align: center;"><%= @users.count %></h1>
                        </div>

               </div>

                <hr width="100%" style="background-color: grey;">

                  <div style="display: flex; justify-content: space-between;">
                        <div>
  
                          <h1 style="color:grey; font-weight: bold; font-size: 35px;margin-bottom: 0px;width: 260.59px;text-align: center; ">USERS</h1>

                            <hr class="hrstyle">
                           <h2 style="color:grey; font-weight: bold; font-size: 20px;margin-bottom: 0px;width: 260.59px;text-align: center; ">DATE:<%= @current_date %></h2> 
                        </div>

                        <div style="width: 50%">
                        </div>

               </div>
                <br>
                <br>
                <br>
                    <div>
                        
                        <table style="color: grey;width: 100%;font-size: 20px;text-align: center;margin-bottom: 100px;">
                            <thead>
                                <tr>
                                    <th>PROFILE</th>
                                    <th>ATTENDANCE</th>
                                    <th>MONEY PAID</th>
                                </tr>
                            </thead>
                            <tbody>
                                <% @users.each do |u| %>
                                    <tr>
                                        <td class='nme' style="font-weight: bold;color: black;"><%=link_to "#{u.name}",users_profile_path(u.user_id),method: :get,style: 'font-size:20px;text-decoration:none;'%>  </td>
                                        <td>
                                            <% stat= Attendanceentre.where(user_id:u.user_id,status:1,date:@current_date) %>
                                            <% if(stat.blank?) %>
                                            <%=link_to "<span>Absent&nbsp; <i class='fa fa-times'></i></span>".html_safe,entres_attend_create_path(u.user_id),method: :post,class: 'mark_attend'%>
                                            <% else %>
                                            <%=link_to "<span class='marked'>Present &nbsp; <i class='fa fa-check'></i></span>".html_safe,entres_attend_destroy_path(u.user_id),method: :post,class: "under"%>
                                            <% end %>
                                        </td>
                                        <td><%= u.fees %></td>
                                    </tr>
                                <% end %>
                            </tbody>
                        </table>

                    </div>
                </div>
            </section>
            <!-- End Section -->

            
            
            <!-- Divider -->
            <hr class="mt-0 mb-0 "/>
            <!-- End Divider -->
            



                        <!-- Footer -->
            <footer class="page-section bg-gray-lighter footer pb-40" style="padding-top: 50px;">
                <div style="display: flex; justify-content: space-around;">
                    
                    <div style="width: 20%;text-align: center; color: black;letter-spacing: 0.2em;">
                        <hr class="hrstyle">
                        <h2>ABOUT ENACTUS DTU</h2>
                        <p>WE, at Enactus DTU, apply entrepreneurial concepts to develop dynamic projects that take advantage of people’s inherent dexterity and aptitude at the center of improving their livelihoods.</p>
                        <hr class="hrstyle">
                    </div>

                    <div>
                                <!-- Footer Logo -->
                                <div style="display: flex;justify-content: center;">
                                    <div class="local-scroll wow fadeInUp" data-wow-duration="1.2s" style="width: 50%;">
                                        <a href="#top"><img src="/assets/Unnati.png" width="150" height="150" alt="" /></a>&nbsp;
                                    </div>
                                </div>
                                <!-- End Footer Logo -->

                                <div style="display: flex;justify-content: center;margin-bottom: 20px; ">
                                 <div style="width: 1px;height:50px;background-color:grey">
                                     
                                 </div>
                              </div>

                                <!-- Social Links -->
                                <div class="footer-social-links mb-xs-40">
                                    <a title="Facebook" target="_blank"><i class="fa fa-facebook"></i></a>
                                    <a title="Twitter" target="_blank"><i class="fa fa-twitter"></i></a>
                                    <a title="Instagarm" target="_blank"><i class="fa fa-instagram"></i></a>
                                    <a title="wordpress" target="_blank"><i class="fa fa-wordpress"></i></a>
                                    <a title="Linkedin" target="_blank"><i class="fa fa-linkedin"></i></a>

                                </div>
                                <!-- End Social Links -->  
                                
                                <div style="display: flex;justify-content: center;margin-top:20px;margin-bottom: 10px; ">
                                 <div style="width: 1px;height:50px;background-color:grey">
                                     
                                 </div>
                              </div>
                                <!-- Footer Text -->
                                <div class="footer-text">
                                    <div class="footer-made">
                                        Made With <span style="color: #e25555;">&hearts;</span> by Enactus, Delhi Technological University
                                    </div>
                                </div>
                        <!-- End Footer Text --> 
                        

                     </div>


                     <div style="width: 20%;text-align: center; color: black;letter-spacing: 0.2em;">
                      
                      <hr class="hrstyle">
                       <h2 style="margin-bottom: 5px;">FACING AN ISSUE?</h2>
                        <h4>CONTACT US</h4>
                        <p>Mail Us:<br><a HREF="mailto:unnati.enactus.dtu@gmail.com">unnati.enactus.dtu@gmail.com</a></p>
                         <hr class="hrstyle">

                     </div>


                </div>
            </footer>

            <!-- End Footer -->
        
        
        </div>
        <!-- End Page Wrap -->
        
        
        <!-- JS -->
        <script type="text/javascript" src="/assets/jquery-1.11.2.min.js"></script>
        <script type="text/javascript" src="/assets/jquery.easing.1.3.js"></script>
        <script type="text/javascript" src="/assets/bootstrap.min.js"></script>
        <script type="text/javascript" src="/assets/SmoothScroll.js"></script>
        <script type="text/javascript" src="/assets/jquery.scrollTo.min.js"></script>
        <script type="text/javascript" src="/assets/jquery.localScroll.min.js"></script>
        <script type="text/javascript" src="/assets/jquery.viewport.mini.js"></script>
        <script type="text/javascript" src="/assets/jquery.countTo.js"></script>
        <script type="text/javascript" src="/assets/jquery.appear.js"></script>
        <script type="text/javascript" src="/assets/jquery.sticky.js"></script>
        <script type="text/javascript" src="/assets/jquery.parallax-1.1.3.js"></script>
        <script type="text/javascript" src="/assets/jquery.fitvids.js"></script>
        <script type="text/javascript" src="/assets/owl.carousel.min.js"></script>
        <script type="text/javascript" src="/assets/isotope.pkgd.min.js"></script>
        <script type="text/javascript" src="/assets/imagesloaded.pkgd.min.js"></script>
        <script type="text/javascript" src="/assets/jquery.magnific-popup.min.js"></script>
        <!-- Replace test API Key "AIzaSyAZsDkJFLS0b59q7cmW0EprwfcfUA8d9dg" with your own one below 
        **** You can get API Key here - https://developers.google.com/maps/documentation/javascript/get-api-key -->
        <script type="text/javascript" src="/assets/wow.min.js"></script>
        <script type="text/javascript" src="/assets/masonry.pkgd.min.js"></script>
        <script type="text/javascript" src="/assets/jquery.simple-text-rotator.min.js"></script>
        <script type="text/javascript" src="/assets/all.js"></script>
        <script type="text/javascript" src="/assets/contact-form.js"></script>
        <script type="text/javascript" src="/assets/jquery.ajaxchimp.min.js"></script>
        <!--[if lt IE 10]>
                <script type="text/javascript" src="/assets/placeholder.js"></script><![endif]-->

<script src="/assets/main.js"></script> <!-- Resource jQuery -->
    </body>
</html>